openapi: 3.2.0
info:
  title: Alayacare message sys_admin API
  version: '1.0'
servers:
- url: https://api.{env}.alayamarket.{region}/offers
  variables:
    env:
      description: The server environment.
      enum:
      - staging
      - sandbox
      - prod
      default: prod
    region:
      description: The server top-level domain indicating the region.
      enum:
      - ca
      - com
      - com.au
      default: ca
security:
- CognitoAuthorizer: []
tags:
- name: message sys_admin
paths:
  /v1/sys_admin/messages:
    get:
      tags:
      - message sys_admin
      description: '# Authorization

        Required role: `sys_admin`


        # Description

        Get a paginated collection of messages for a sequence as a system admin.

        '
      parameters:
      - $ref: '#/components/parameters/SequenceIdQueryParam'
      - $ref: '#/components/parameters/MessageSenderTypeQueryParam'
      - $ref: '#/components/parameters/MessageCategoryQueryParam'
      - $ref: '#/components/parameters/PageNumberParam'
      - $ref: '#/components/parameters/ItemsPerPageParam'
      - in: query
        name: sort_by
        schema:
          type: string
          enum:
          - created_at
          default: created_at
      - $ref: '#/components/parameters/SortOrderParam'
      responses:
        200:
          description: Successfully returned messages.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SysAdminMessagePageResponse'
      x-amazon-apigateway-integration:
        uri:
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${OfferApiFunctionV2.Arn}:live/invocations
        httpMethod: POST
        passthroughBehavior: when_no_match
        type: aws_proxy
  /v1/sys_admin/messages/by_file_id/{file_id}:
    parameters:
    - $ref: '#/components/parameters/FileIdPathParam'
    get:
      tags:
      - message sys_admin
      description: '# Authorization

        Required role: `sys_admin`


        # Description

        Get a message by file ID.

        '
      responses:
        200:
          description: Successfully returned a message.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SysAdminMessageDetailResponse'
      x-amazon-apigateway-integration:
        uri:
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${OfferApiFunctionV2.Arn}:live/invocations
        httpMethod: POST
        passthroughBehavior: when_no_match
        type: aws_proxy
components:
  schemas:
    MessageSenderTypeCore:
      type: string
      enum:
      - demand
      - supply
    ItemsPerPageCore:
      type: integer
      minimum: 1
      default: 100
    MessageCategoryCore:
      type: string
      enum:
      - client_attachment
      - comment
    SysAdminMessageDetailResponse:
      properties:
        message:
          type: object
          title: SysAdminMessageDetailMessageResponse
          properties:
            id:
              type: string
              format: uuid
            sequence_id:
              type: string
              format: uuid
            category:
              $ref: '#/components/schemas/MessageCategoryCore'
            sender_type:
              $ref: '#/components/schemas/MessageSenderTypeCore'
            text:
              type: string
              maxLength: 2500
            author:
              type: string
              maxLength: 100
            created_at:
              type: string
              format: date-time
            file:
              type: object
              title: SysAdminMessageDetailFileResponse
              properties:
                id:
                  type: string
                  format: uuid
                url:
                  type: string
                name:
                  type: string
                size_in_bytes:
                  type: integer
                  minimum: 0
                  maximum: 52428800
              required:
              - id
              - url
              - name
          required:
          - id
          - sequence_id
          - category
          - sender_type
          - created_at
        sender:
          type: object
          title: SysAdminMessageDetailSenderResponse
          properties:
            id:
              type: string
              format: uuid
            name:
              type: string
          required:
          - id
          - name
        recipient:
          type: object
          title: SysAdminMessageDetailRecipientResponse
          properties:
            id:
              type: string
              format: uuid
            name:
              type: string
          required:
          - id
          - name
      required:
      - message
      - sender
      - recipient
    PageCore:
      description: Root page schema for returning collections.
      type: object
      properties:
        page:
          $ref: '#/components/schemas/PageNumberCore'
        items_per_page:
          $ref: '#/components/schemas/ItemsPerPageCore'
        total_items:
          type: integer
          minimum: 0
        total_pages:
          type: integer
          minimum: 0
      required:
      - page
      - items_per_page
      - total_items
      - total_pages
    SortOrderCore:
      type: string
      enum:
      - asc
      - desc
      default: desc
    PageNumberCore:
      type: integer
      minimum: 1
      default: 1
    SysAdminMessagePageResponse:
      allOf:
      - $ref: '#/components/schemas/PageCore'
      - type: object
        properties:
          items:
            type: array
            items:
              $ref: '#/components/schemas/SysAdminMessageDetailResponse'
        required:
        - items
  parameters:
    MessageSenderTypeQueryParam:
      in: query
      name: sender_type
      schema:
        $ref: '#/components/schemas/MessageSenderTypeCore'
    MessageCategoryQueryParam:
      in: query
      name: category
      schema:
        $ref: '#/components/schemas/MessageCategoryCore'
    FileIdPathParam:
      in: path
      name: file_id
      schema:
        type: string
        format: uuid
      required: true
      description: ID of a file.
    ItemsPerPageParam:
      in: query
      name: items_per_page
      schema:
        $ref: '#/components/schemas/ItemsPerPageCore'
    PageNumberParam:
      in: query
      name: page
      schema:
        $ref: '#/components/schemas/PageNumberCore'
    SequenceIdQueryParam:
      in: query
      name: sequence_id
      schema:
        type: string
        format: uuid
      required: true
    SortOrderParam:
      in: query
      name: sort_order
      schema:
        $ref: '#/components/schemas/SortOrderCore'
  securitySchemes:
    CognitoAuthorizer:
      type: apiKey
      name: Authorization
      in: header
      x-amazon-apigateway-authtype: cognito_user_pools
      x-amazon-apigateway-authorizer:
        type: cognito_user_pools
        providerARNs:
        - Fn::Sub: '{{resolve:ssm:/${StackName}/${UserPoolArnSSMParameterName}}}'
x-amazon-apigateway-request-validators:
  body:
    validateRequestBody: true
    validateRequestParameters: false
  params:
    validateRequestBody: false
    validateRequestParameters: true
  params-and-body:
    validateRequestBody: true
    validateRequestParameters: true
x-amazon-apigateway-request-validator: params
x-amazon-apigateway-gateway-responses:
  BAD_REQUEST_BODY:
    statusCode: 400
    responseTemplates:
      application/json: '{"message": $context.error.messageString, "description": "$context.error.validationErrorString"}'
