openapi: 3.2.0
info:
  title: Alayacare form submission inbox API
  version: '1.0'
servers:
- url: https://api.{env}.alayamarket.{region}/offers
  variables:
    env:
      description: The server environment.
      enum:
      - staging
      - sandbox
      - prod
      default: prod
    region:
      description: The server top-level domain indicating the region.
      enum:
      - ca
      - com
      - com.au
      default: ca
security:
- CognitoAuthorizer: []
tags:
- name: form submission inbox
paths:
  /v1/inbox/form_submissions:
    post:
      tags:
      - form submission inbox
      description: '# Authorization

        Required role: supply `org_admin` assigned to the associated referral.


        # Description

        Save a form submission.


        One of `service_id` or `visit_id` must be provided.

        '
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InboxFormSubmissionCreationRequest'
      responses:
        201:
          description: Successfully created form submission.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InboxFormSubmissionCreationResponse'
      x-amazon-apigateway-integration:
        uri:
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${OfferApiFunctionV2.Arn}:live/invocations
        httpMethod: POST
        passthroughBehavior: when_no_match
        type: aws_proxy
components:
  schemas:
    FormSubmissionHiddenFieldCore:
      type: object
      properties:
        field_id:
          type: string
          format: uuid
      required:
      - field_id
    InboxFormSubmissionCreationResponse:
      type: object
      properties:
        form_template_id:
          type: string
          format: uuid
        id:
          type: string
          format: uuid
        service_id:
          type: string
          format: uuid
        visit_id:
          type: string
          format: uuid
        work_session_id:
          type: string
          format: uuid
        fields:
          type: array
          items:
            $ref: '#/components/schemas/InboxFormSubmissionFieldCore'
          minItems: 1
        hidden_fields:
          type: array
          items:
            $ref: '#/components/schemas/FormSubmissionHiddenFieldCore'
      required:
      - id
      - form_template_id
      - fields
    InboxFormSubmissionFieldCore:
      type: object
      properties:
        field_id:
          type: string
          format: uuid
        value_type:
          type: string
          enum:
          - attachment
          - boolean
          - decimal
          - json
          - string
        value:
          type: string
      required:
      - field_id
      - value_type
      - value
    InboxFormSubmissionCreationRequest:
      type: object
      properties:
        form_template_id:
          type: string
          format: uuid
        service_id:
          type: string
          format: uuid
        visit_id:
          type: string
          format: uuid
        work_session_id:
          type: string
          format: uuid
        fields:
          type: array
          items:
            $ref: '#/components/schemas/InboxFormSubmissionFieldCore'
          minItems: 1
        hidden_fields:
          type: array
          items:
            $ref: '#/components/schemas/FormSubmissionHiddenFieldCore'
      required:
      - form_template_id
      - fields
  securitySchemes:
    CognitoAuthorizer:
      type: apiKey
      name: Authorization
      in: header
      x-amazon-apigateway-authtype: cognito_user_pools
      x-amazon-apigateway-authorizer:
        type: cognito_user_pools
        providerARNs:
        - Fn::Sub: '{{resolve:ssm:/${StackName}/${UserPoolArnSSMParameterName}}}'
x-amazon-apigateway-request-validators:
  body:
    validateRequestBody: true
    validateRequestParameters: false
  params:
    validateRequestBody: false
    validateRequestParameters: true
  params-and-body:
    validateRequestBody: true
    validateRequestParameters: true
x-amazon-apigateway-request-validator: params
x-amazon-apigateway-gateway-responses:
  BAD_REQUEST_BODY:
    statusCode: 400
    responseTemplates:
      application/json: '{"message": $context.error.messageString, "description": "$context.error.validationErrorString"}'
