openapi: 3.0.0
info:
  version: 1.0.19-oas3
  title: AlayaCare Accounting Accounts Activity Codes API
  description: '**AlayaCare IDs:**

    The following terms are used to reference IDs that identify resources in AlayaCare:

    - id

    - visit_id

    - premium_id

    - visit_premium_id

    - employee_id

    - cost_centre_id

    - client_id


    **External IDs**

    The following terms are used to reference IDs that identify resources systems external to AlayaCare:

    - employee_external_id

    - client_external_id


    External IDs are required to be unique.

    No other assumptions are made regarding their format they are treated as strings.

    '
servers:
- url: https://example.alayacare.com/ext/api/v2/accounting
security:
- basic_auth: []
tags:
- name: Activity Codes
paths:
  /activity_codes:
    get:
      tags:
      - Activity Codes
      parameters:
      - $ref: '#/components/parameters/page'
      - $ref: '#/components/parameters/count'
      - name: filter
        in: query
        description: Filter by activity codes Code and Description fields.
        schema:
          type: string
      summary: Get a list of activity codes
      responses:
        '200':
          description: A list of activity codes
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ActivityCodeList'
        '401':
          $ref: '#/components/responses/ErrorResponseAuthentication'
components:
  schemas:
    BranchSummary:
      description: Branch summary
      type: object
      properties:
        id:
          type: integer
          description: ID of the branch
          example: 1
          minimum: 1
        name:
          type: string
          description: Name of the branch
          example: Headquarters
    PaginatedList:
      description: Base model of all paginated lists
      type: object
      properties:
        count:
          type: integer
          description: Number of items in the response
          example: 10
        page:
          type: integer
          description: Current page number
          example: 1
          minimum: 1
        total_pages:
          type: integer
          description: Total number of pages available
          example: 1
        items:
          type: array
          items:
            type: object
      required:
      - count
      - page
      - total_pages
      - items
    ActivityCode:
      description: Details of a cost centre
      type: object
      properties:
        description:
          type: string
          description: Activity Code description
          example: Some description
        id:
          type: integer
          description: Activity Code ID
          example: 2
        code:
          type: string
          description: Activity Code code field
          example: '5555'
        branch:
          $ref: '#/components/schemas/BranchSummary'
      nullable: true
    ErrorResponse:
      description: Error response
      type: object
      properties:
        code:
          type: integer
          example: 400
          description: Response code
        message:
          type: string
          example: Invalid request
          description: Detailed error message
      required:
      - code
      - message
    ActivityCodeList:
      allOf:
      - $ref: '#/components/schemas/PaginatedList'
      description: Paginated list of activity codes
      type: object
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/ActivityCode'
  responses:
    ErrorResponseAuthentication:
      description: Authorization required
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
          examples:
            response:
              value:
                code: '401'
                message: Authorization required.
  parameters:
    count:
      description: Number of items per page.
      name: count
      in: query
      required: false
      schema:
        type: integer
        default: 100
    page:
      description: Filter by page number.
      name: page
      in: query
      required: false
      schema:
        type: integer
        default: 1
        minimum: 1
  securitySchemes:
    basic_auth:
      type: http
      description: Basic HTTP auth over https
      scheme: basic
