openapi: 3.2.0
info:
  title: Alayacare form template inbox API
  version: '1.0'
servers:
- url: https://api.{env}.alayamarket.{region}/offers
  variables:
    env:
      description: The server environment.
      enum:
      - staging
      - sandbox
      - prod
      default: prod
    region:
      description: The server top-level domain indicating the region.
      enum:
      - ca
      - com
      - com.au
      default: ca
security:
- CognitoAuthorizer: []
tags:
- name: form template inbox
paths:
  /v1/inbox/form_templates/by_demand_persona_id/{demand_persona_id}/by_schema_id/{schema_id}/latest:
    parameters:
    - $ref: '#/components/parameters/DemandPersonaIdPathParam'
    - $ref: '#/components/parameters/FormSchemaIdPathParam'
    get:
      tags:
      - form template inbox
      description: '# Authorization

        Required role: supply `org_admin` in the trusted network

        of the demand organization of the form.


        # Description

        Returns the latest form version available for a given schema_id within a demand organization.

        '
      responses:
        200:
          description: Successfully retrieved the form template.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InboxFormTemplateDetailResponse'
      x-amazon-apigateway-integration:
        uri:
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${OfferApiFunctionV2.Arn}:live/invocations
        httpMethod: POST
        passthroughBehavior: when_no_match
        type: aws_proxy
components:
  parameters:
    FormSchemaIdPathParam:
      in: path
      name: schema_id
      schema:
        type: string
        format: uuid
      required: true
      description: Schema id of a form.
    DemandPersonaIdPathParam:
      in: path
      name: demand_persona_id
      schema:
        type: string
        format: uuid
      required: true
      description: ID of a demand organization.
  schemas:
    FormTemplateCore:
      type: object
      properties:
        admin_eyes_only:
          type: boolean
        approve_automatically:
          type: boolean
        clinical_event_name:
          type: string
        display_instructions_in_pdf:
          type: boolean
        display_report:
          type: boolean
        exclude_from_shift_report:
          type: boolean
        form_type:
          type: string
        id:
          type: integer
        instructions:
          type: string
        language_code:
          type: string
        name:
          type: string
        notify_alert_queue:
          type: boolean
        pre_populate:
          type: boolean
        requires_clock_in:
          type: boolean
        schema_id:
          type: string
          format: uuid
        schema_version:
          type: integer
        visit_link_required:
          type: boolean
      required:
      - admin_eyes_only
      - approve_automatically
      - display_instructions_in_pdf
      - display_report
      - exclude_from_shift_report
      - form_type
      - id
      - language_code
      - name
      - notify_alert_queue
      - pre_populate
      - requires_clock_in
      - schema_id
      - schema_version
      - visit_link_required
    InboxFormTemplateFieldResponse:
      allOf:
      - $ref: '#/components/schemas/FormTemplateFieldCore'
      - type: object
        properties:
          field_id:
            type: string
            format: uuid
    FormTemplateFieldCore:
      type: object
      properties:
        field_tag:
          type: string
        field_type:
          type: string
        id:
          type: integer
        instructions:
          type: string
        json_logic:
          type: object
        label:
          type: string
        parent_id:
          type: integer
        rank:
          type: integer
        required:
          type: boolean
        settings:
          type: object
      required:
      - field_type
      - id
      - label
      - parent_id
      - rank
      - required
    InboxFormTemplateDetailResponse:
      allOf:
      - $ref: '#/components/schemas/FormTemplateCore'
      - type: object
        properties:
          fields:
            type: array
            items:
              $ref: '#/components/schemas/InboxFormTemplateFieldResponse'
          form_template_id:
            type: string
            format: uuid
          demand_persona_id:
            type: string
            format: uuid
  securitySchemes:
    CognitoAuthorizer:
      type: apiKey
      name: Authorization
      in: header
      x-amazon-apigateway-authtype: cognito_user_pools
      x-amazon-apigateway-authorizer:
        type: cognito_user_pools
        providerARNs:
        - Fn::Sub: '{{resolve:ssm:/${StackName}/${UserPoolArnSSMParameterName}}}'
x-amazon-apigateway-request-validators:
  body:
    validateRequestBody: true
    validateRequestParameters: false
  params:
    validateRequestBody: false
    validateRequestParameters: true
  params-and-body:
    validateRequestBody: true
    validateRequestParameters: true
x-amazon-apigateway-request-validator: params
x-amazon-apigateway-gateway-responses:
  BAD_REQUEST_BODY:
    statusCode: 400
    responseTemplates:
      application/json: '{"message": $context.error.messageString, "description": "$context.error.validationErrorString"}'
