openapi: 3.2.0
info:
  title: Alayacare offer status API
  version: '1.0'
servers:
- url: https://api.{env}.alayamarket.{region}/offers
  variables:
    env:
      description: The server environment.
      enum:
      - staging
      - sandbox
      - prod
      default: prod
    region:
      description: The server top-level domain indicating the region.
      enum:
      - ca
      - com
      - com.au
      default: ca
security:
- CognitoAuthorizer: []
tags:
- name: offer status
paths:
  /v1/status/healthz:
    get:
      tags:
      - offer status
      responses:
        200:
          description: Current healthz status
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StatusHealthzResponse'
      security:
      - NONE: []
      x-amazon-apigateway-integration:
        uri:
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${OfferApiFunctionV2.Arn}:live/invocations
        httpMethod: POST
        passthroughBehavior: when_no_match
        type: aws_proxy
components:
  schemas:
    StatusHealthzResponse:
      type: object
      properties:
        status:
          type: string
      required:
      - status
  securitySchemes:
    CognitoAuthorizer:
      type: apiKey
      name: Authorization
      in: header
      x-amazon-apigateway-authtype: cognito_user_pools
      x-amazon-apigateway-authorizer:
        type: cognito_user_pools
        providerARNs:
        - Fn::Sub: '{{resolve:ssm:/${StackName}/${UserPoolArnSSMParameterName}}}'
x-amazon-apigateway-request-validators:
  body:
    validateRequestBody: true
    validateRequestParameters: false
  params:
    validateRequestBody: false
    validateRequestParameters: true
  params-and-body:
    validateRequestBody: true
    validateRequestParameters: true
x-amazon-apigateway-request-validator: params
x-amazon-apigateway-gateway-responses:
  BAD_REQUEST_BODY:
    statusCode: 400
    responseTemplates:
      application/json: '{"message": $context.error.messageString, "description": "$context.error.validationErrorString"}'
