openapi: 3.2.0
info:
  title: Patients - Clients Service Status API
  version: 1.0.18-oas3
  description: '**AlayaCare IDs:**

    The following terms are used to reference IDs that identify resources in AlayaCare:

    - client_id

    - status_id

    - contact_id


    **External IDs**

    The following terms are used to reference IDs that identify resources systems external to AlayaCare:

    - external_client_id

    - external_contact_id


    External IDs are required to be unique.

    No other assumptions are made regarding their format they are treated as strings.

    External IDs are unique to a single profile_id.


    **Profile IDs**

    The following term is used to describe a profile resource in AlayaCare:

    - profile_id


    Profile IDs can be shared across clients, contacts, and employees in the

    case that an entity shares one or more of those roles.


    **Client Status Considerations**

    - Clients can have multiple status configured depending on their business needs. Rules for configuring client status follow the internal AlayaCare application logic.

    - Updating the `status` of a client will have repercussions in the AlayaCare application.


    Please refer to this link for more information: https://alayacare.zendesk.com/hc/en-us/articles/360015538392

    '
  contact:
    name: AlayaCare
servers:
- url: '{server}/ext/api/v2/patients'
  variables:
    server:
      default: https://demo3.alayacare.ca
tags:
- name: Service Status
  description: Service status related endpoints.
paths:
  /service/{service_id}/status:
    post:
      tags:
      - Service Status
      summary: Create a service status
      operationId: createServiceStatus
      description: Creates a service status for a service by service ID.
      parameters:
      - name: service_id
        description: ID of the service
        in: path
        required: true
        schema:
          type: integer
      requestBody:
        $ref: '#/components/requestBodies/ServiceStatusCreate'
      responses:
        '201':
          description: Service status created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceStatusCreate'
        '400':
          $ref: '#/components/responses/ErrorResponseClientStatusInvalidRequest'
        '401':
          $ref: '#/components/responses/ErrorResponseAuthentication'
  /service/by_id/{external_service_id}/status:
    post:
      tags:
      - Service Status
      summary: Create a service status using external client id
      operationId: createServiceStatusByExt
      description: Creates a service status for a service by external service ID.
      parameters:
      - name: external_service_id
        description: External ID of the service
        in: path
        required: true
        schema:
          type: integer
      requestBody:
        $ref: '#/components/requestBodies/ServiceStatusCreate'
      responses:
        '201':
          description: Service status created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceStatusCreate'
        '400':
          $ref: '#/components/responses/ErrorResponseClientStatusInvalidRequest'
        '401':
          $ref: '#/components/responses/ErrorResponseAuthentication'
components:
  responses:
    ErrorResponseClientStatusInvalidRequest:
      description: Invalid request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
          examples:
            response:
              value:
                code: 400
                idstatus:
                - Not a valid choice.
                message: Validation error.
    ErrorResponseAuthentication:
      description: Authorization required
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
          examples:
            response:
              value:
                code: 401
                message: Authorization required.
  schemas:
    ErrorResponse:
      description: Error response
      type: object
      properties:
        code:
          type: integer
          example: 400
          description: Response code
        message:
          type: string
          example: Invalid request
          description: Detailed error message
      required:
      - code
      - message
    ServiceStatusCreate:
      type: object
      properties:
        status_id:
          type: string
          description: ID of the status
          enum:
          - active
          - on_hold
          - waiting_list
          - discharged
        upcoming_status_id:
          type:
          - integer
          - 'null'
          description: ID of the upcoming status
        status_reason:
          type:
          - string
          - 'null'
          description: Reason for the status
        status_date:
          type: string
          format: date-time
          example: '2025-02-26T04:32:10.000Z'
          description: Date of the status, set to now if not provided.
        status_end_date:
          type:
          - string
          - 'null'
          format: date-time
          description: End date of the status
      required:
      - status_id
  requestBodies:
    ServiceStatusCreate:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ServiceStatusCreate'
      required: true
  securitySchemes:
    basic_auth:
      type: http
      description: Basic HTTP auth over https
      scheme: basic
