openapi: 3.2.0
info:
  title: Alayacare organization settings API
  version: '1.0'
servers:
- url: https://api.{env}.alayamarket.{region}/offers
  variables:
    env:
      description: The server environment.
      enum:
      - staging
      - sandbox
      - prod
      default: prod
    region:
      description: The server top-level domain indicating the region.
      enum:
      - ca
      - com
      - com.au
      default: ca
security:
- CognitoAuthorizer: []
tags:
- name: organization settings
paths:
  /v1/demand_personas/settings/assignment:
    post:
      tags:
      - organization settings
      description: '# Authorization

        Required role: `org_admin`


        # Description

        Set offer assignment setting for an organization.

        '
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OutboxOfferAssignmentSettingUpdateRequest'
      responses:
        204:
          description: Setting succesfully saved.
      x-amazon-apigateway-integration:
        uri:
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${OfferApiFunctionV2.Arn}:live/invocations
        httpMethod: POST
        passthroughBehavior: when_no_match
        type: aws_proxy
    get:
      tags:
      - organization settings
      description: '# Authorization

        Required role: `org_admin`


        # Description

        Get offer assignment setting for an organization.

        '
      responses:
        200:
          description: Offer assignment setting.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OutboxOfferAssignmentSettingUpdateResponse'
      x-amazon-apigateway-integration:
        uri:
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${OfferApiFunctionV2.Arn}:live/invocations
        httpMethod: POST
        passthroughBehavior: when_no_match
        type: aws_proxy
components:
  schemas:
    OutboxOfferAssignmentSettingUpdateResponse:
      type: object
      properties:
        offer_assignment:
          type: string
          enum:
          - auto
          - manual
      required:
      - offer_assignment
    OutboxOfferAssignmentSettingUpdateRequest:
      type: object
      properties:
        offer_assignment:
          type: string
          enum:
          - auto
          - manual
      required:
      - offer_assignment
  securitySchemes:
    CognitoAuthorizer:
      type: apiKey
      name: Authorization
      in: header
      x-amazon-apigateway-authtype: cognito_user_pools
      x-amazon-apigateway-authorizer:
        type: cognito_user_pools
        providerARNs:
        - Fn::Sub: '{{resolve:ssm:/${StackName}/${UserPoolArnSSMParameterName}}}'
x-amazon-apigateway-request-validators:
  body:
    validateRequestBody: true
    validateRequestParameters: false
  params:
    validateRequestBody: false
    validateRequestParameters: true
  params-and-body:
    validateRequestBody: true
    validateRequestParameters: true
x-amazon-apigateway-request-validator: params
x-amazon-apigateway-gateway-responses:
  BAD_REQUEST_BODY:
    statusCode: 400
    responseTemplates:
      application/json: '{"message": $context.error.messageString, "description": "$context.error.validationErrorString"}'
