openapi: 3.0.0
info:
  version: 1.0.19-oas3
  title: AlayaCare Accounting Accounts Premium Bill Codes API
  description: '**AlayaCare IDs:**

    The following terms are used to reference IDs that identify resources in AlayaCare:

    - id

    - visit_id

    - premium_id

    - visit_premium_id

    - employee_id

    - cost_centre_id

    - client_id


    **External IDs**

    The following terms are used to reference IDs that identify resources systems external to AlayaCare:

    - employee_external_id

    - client_external_id


    External IDs are required to be unique.

    No other assumptions are made regarding their format they are treated as strings.

    '
servers:
- url: https://example.alayacare.com/ext/api/v2/accounting
security:
- basic_auth: []
tags:
- name: Premium Bill Codes
paths:
  /premiums/{premium_id}/bill_codes:
    parameters:
    - name: premium_id
      description: The selected premium id
      in: path
      required: true
      schema:
        type: integer
        minimum: 1
    patch:
      summary: Add or remove from set of Bill Codes linked to a Premium
      tags:
      - Premium Bill Codes
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                bill_codes_to_add:
                  type: array
                  items:
                    $ref: '#/components/schemas/BillCodeStub'
                bill_codes_to_remove:
                  type: array
                  items:
                    $ref: '#/components/schemas/BillCodeStub'
      responses:
        '200':
          description: Premium
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Success'
        '401':
          $ref: '#/components/responses/ErrorResponseAuthentication'
        '403':
          $ref: '#/components/responses/ErrorResponseAccessDenied'
        '404':
          $ref: '#/components/responses/ErrorPremiumNotFound'
components:
  responses:
    ErrorPremiumNotFound:
      description: The premium referenced by visit_id was not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
          examples:
            response:
              value:
                code: '404'
                message: Premium not found
    ErrorResponseAccessDenied:
      description: Access denied
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
          examples:
            response:
              value:
                code: '403'
                message: You do not have the required permissions to perform this action
    ErrorResponseAuthentication:
      description: Authorization required
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
          examples:
            response:
              value:
                code: '401'
                message: Authorization required.
  schemas:
    BillCodeStub:
      type: object
      description: Only one of id or guid should be present
      properties:
        id:
          type: integer
          example: 3
        guid:
          type: integer
          example: 3
    ErrorResponse:
      description: Error response
      type: object
      properties:
        code:
          type: integer
          example: 400
          description: Response code
        message:
          type: string
          example: Invalid request
          description: Detailed error message
      required:
      - code
      - message
    Success:
      type: object
      properties:
        message:
          type: string
          example: Success
  securitySchemes:
    basic_auth:
      type: http
      description: Basic HTTP auth over https
      scheme: basic
