openapi: 3.2.0
info:
  title: Alayacare work session inbox API
  version: '1.0'
servers:
- url: https://api.{env}.alayamarket.{region}/offers
  variables:
    env:
      description: The server environment.
      enum:
      - staging
      - sandbox
      - prod
      default: prod
    region:
      description: The server top-level domain indicating the region.
      enum:
      - ca
      - com
      - com.au
      default: ca
security:
- CognitoAuthorizer: []
tags:
- name: work session inbox
paths:
  /v1/inbox/work_sessions/start:
    post:
      tags:
      - work session inbox
      description: '# Authorization

        Required role: `org_admin` assigned to the associated referral.


        # Description

        Start a Work Session for a given visit.


        One of `visit_id` or `visit_inbox_id` must be provided.

        '
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InboxWorkSessionStartRequest'
      responses:
        201:
          description: Successfully started a Work Session.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InboxWorkSessionStartResponse'
      x-amazon-apigateway-integration:
        uri:
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${OfferApiFunctionV2.Arn}:live/invocations
        httpMethod: POST
        passthroughBehavior: when_no_match
        type: aws_proxy
  /v1/inbox/work_sessions/end:
    post:
      tags:
      - work session inbox
      description: '# Authorization

        Required role: `org_admin` who started the Work Session.


        # Description

        End a Work Session.


        * One of `work_session_id` or `inbox_id` must be provided, AND

        * One of `visit_id` or `visit_inbox_id` must be provided.

        '
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InboxWorkSessionEndRequest'
      responses:
        204:
          description: Successfully ended a Work Session.
      x-amazon-apigateway-integration:
        uri:
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${OfferApiFunctionV2.Arn}:live/invocations
        httpMethod: POST
        passthroughBehavior: when_no_match
        type: aws_proxy
components:
  schemas:
    InboxWorkSessionStartResponse:
      allOf:
      - $ref: '#/components/schemas/InboxWorkSessionStartRequest'
      type: object
      properties:
        id:
          type: string
          format: uuid
          description: Work Session ID.
      required:
      - id
    InboxWorkSessionStartRequest:
      type: object
      properties:
        start_at:
          type: string
          format: date-time
        start_latitude:
          type: number
          format: double
          minimum: -90
          maximum: 90
        start_longitude:
          type: number
          format: double
          minimum: -180
          maximum: 180
        visit_id:
          type: string
          format: uuid
        visit_inbox_id:
          type: string
        inbox_id:
          type: string
          minLength: 1
      required:
      - start_at
      - inbox_id
    InboxWorkSessionEndRequest:
      type: object
      properties:
        end_at:
          type: string
          format: date-time
        work_session_id:
          type: string
          format: uuid
        end_latitude:
          type: number
          format: double
          minimum: -90
          maximum: 90
        end_longitude:
          type: number
          format: double
          minimum: -180
          maximum: 180
        visit_id:
          type: string
          format: uuid
        visit_inbox_id:
          type: string
        inbox_id:
          type: string
      required:
      - end_at
  securitySchemes:
    CognitoAuthorizer:
      type: apiKey
      name: Authorization
      in: header
      x-amazon-apigateway-authtype: cognito_user_pools
      x-amazon-apigateway-authorizer:
        type: cognito_user_pools
        providerARNs:
        - Fn::Sub: '{{resolve:ssm:/${StackName}/${UserPoolArnSSMParameterName}}}'
x-amazon-apigateway-request-validators:
  body:
    validateRequestBody: true
    validateRequestParameters: false
  params:
    validateRequestBody: false
    validateRequestParameters: true
  params-and-body:
    validateRequestBody: true
    validateRequestParameters: true
x-amazon-apigateway-request-validator: params
x-amazon-apigateway-gateway-responses:
  BAD_REQUEST_BODY:
    statusCode: 400
    responseTemplates:
      application/json: '{"message": $context.error.messageString, "description": "$context.error.validationErrorString"}'
